name: Build Kivy Application for Windows with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Chạy trên Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies for Kivy and PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install kivy pyinstaller

      - name: Build Application with PyInstaller
        run: |
          pyinstaller --onefile main.py  # Đóng gói ứng dụng với PyInstaller

      - name: Upload Build Artifact (Windows .exe)
        uses: actions/upload-artifact@v3
        with:
          name: kivy-windows-build
          path: dist/main.exe  # Đảm bảo tên tệp đúng, mặc định là 'main.exe'
