name: Build Kivy Android APK on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Dùng macOS runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew update

      - name: Install dependencies for Buildozer
        run: |
          brew install python@3.10
          brew install openjdk@11
          brew install android-sdk
          brew install libjpeg
          brew install pkg-config
          brew install sdl2
          brew install libpng
          brew install cairo
          brew install libffi
          brew install coreutils

      - name: Install Kivy and Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install kivy buildozer
          buildozer --version  # Check if buildozer is installed

      - name: Set up Android SDK and NDK
        run: |
          export ANDROID_HOME="/usr/local/opt/android-sdk"
          echo "sdk.dir=$ANDROID_HOME" > $PWD/local.properties

          # Install Android SDK components
          yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
          $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "android-29"
          export PATH=$PATH:$ANDROID_HOME/tools/bin

      - name: Run Buildozer to Build APK
        run: |
          buildozer android debug  # Generate APK using Buildozer
