name: Build Kivy App with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtk-3-0 libglib2.0-0 libsm6 libxext6 libxrender-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy --no-cache-dir
        pip install pyinstaller --no-cache-dir

    - name: Check installed packages
      run: pip list

    - name: Run PyInstaller to build the app
      run: pyinstaller --onefile main.py

    - name: List files in dist folder
      run: ls -l dist/

    - name: Commit the built files back to repository
      run: |
        # Cài đặt git và cấu hình thông tin người dùng
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

        # Thêm các file đã build vào git (trừ main.py vì nó đã có trong .gitignore)
        git add dist/*  # Đảm bảo rằng chỉ file trong thư mục dist được commit

        # Kiểm tra xem có thay đổi nào không trước khi commit
        git diff --exit-code dist/* || git commit -m "Add built application files"

        # Đẩy lên repo
        git push origin main
