name: Build Kivy Android APK on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Dùng macOS runner
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies for Buildozer
        run: |
          brew install python@3.10
          brew install openjdk@11
          brew install libjpeg
          brew install pkg-config
          brew install sdl2
          brew install libpng
          brew install cairo
          brew install libffi
          brew install coreutils

      - name: Install Kivy and Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install kivy buildozer
          pip install cython  # Cài Cython tại đây
          buildozer --version  # Kiểm tra nếu buildozer đã được cài đặt

      - name: Set up Java environment (JDK 11)
        run: |
          export JAVA_HOME=$(/usr/libexec/java_home -v 11)
          export PATH=$JAVA_HOME/bin:$PATH
          echo "JAVA_HOME is set to $JAVA_HOME"

      - name: Run Buildozer to Build APK
        run: |
          buildozer android debug  # Tạo APK bằng Buildozer
