name: Build Kivy App with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtk-3-0 libglib2.0-0 libsm6 libxext6 libxrender-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy --no-cache-dir
        pip install pyinstaller --no-cache-dir

    - name: Check installed packages
      run: pip list

    - name: Run PyInstaller to build the app
      run: pyinstaller --onefile main.py

    - name: List files in dist folder
      run: ls -l dist/

    - name: Upload the built application as artifact
      uses: actions/upload-artifact@v3
      with:
        name: kivy-app
        path: dist/main.exe

    - name: Commit and push built .exe file to the repository
      run: |
        # Add the .exe file to the repo and commit it
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

        # Create a new branch (or use an existing one)
        git checkout -b build-artifacts

        # Copy .exe file to the repository
        cp dist/main.exe .

        # Add and commit the file
        git add main.exe
        git commit -m "Add built .exe file"

        # Push the file to the repository (create a new branch or push to an existing branch)
        git push origin build-artifacts

