name: Build Ứng dụng Kivy cho Debian bằng PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên Ubuntu, nhưng chúng ta sẽ sử dụng Docker container Debian

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Thiết lập Docker với Debian
        run: |
          docker pull debian:latest  # Kéo Docker image Debian mới nhất
          docker run --rm -v $PWD:/workspace -w /workspace debian:latest bash -c "
            apt-get update &&
            apt-get install -y python3 python3-pip python3-venv &&
            pip install --upgrade pip &&
            pip install kivy pyinstaller &&
            pyinstaller --onefile main.py
          "  # Cài đặt các thư viện và chạy PyInstaller trong môi trường Debian

      - name: Upload Build Artifact (file nhị phân cho Debian)
        uses: actions/upload-artifact@v3
        with:
          name: kivy-debian-build
          path: dist/main  # Đảm bảo tên tệp đúng, là file nhị phân chạy trên Debian
