name: Build Ứng dụng Kivy cho Ubuntu bằng PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cài đặt Python và tạo môi trường ảo
        run: |
          # Cập nhật và cài đặt Python3, pip, và môi trường ảo
          sudo apt update
          sudo apt install -y python3.10 python3.10-venv python3-pip
          python3.10 -m venv venv  # Tạo môi trường ảo
          source venv/bin/activate  # Kích hoạt môi trường ảo

      - name: Cài đặt các thư viện phụ thuộc cho Kivy và PyInstaller
        run: |
          source venv/bin/activate  # Kích hoạt lại môi trường ảo
          pip install --upgrade pip
          pip install kivy pyinstaller

      - name: Build ứng dụng bằng PyInstaller
        run: |
          source venv/bin/activate  # Kích hoạt lại môi trường ảo
          pyinstaller --onefile main.py  # Đóng gói ứng dụng thành file nhị phân

      - name: Upload Build Artifact (file nhị phân cho Ubuntu)
        uses: actions/upload-artifact@v3
        with:
          name: kivy-ubuntu-build
          path: dist/main  # Đảm bảo tên tệp đúng cho file nhị phân trên Ubuntu
